# Generated by Django 3.1.2 on 2020-10-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favourate',
            field=models.BooleanField(default=False),
        ),
    ]
